schema = 3

[mod]
  [mod.'github.com/Masterminds/semver/v3']
    version = 'v3.5.0'
    hash = 'sha256-Ps7gEw0nkHDZO/iDru/s+X8rMaUkNmiZ7id1GsIKlDU='

  [mod.'github.com/aws/aws-sdk-go-v2']
    version = 'v1.42.0'
    hash = 'sha256-NAB0Xf/I0LfFbi01v2Z5FTnbLyqOn9t4Ao0aBzS5hF4='

  [mod.'github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream']
    version = 'v1.7.13'
    hash = 'sha256-VgXaGmkg9zBu1zqZ+mIdGKnn2KO4485JHxC0fPuU258='

  [mod.'github.com/aws/aws-sdk-go-v2/credentials']
    version = 'v1.19.24'
    hash = 'sha256-anvHM7aJJZnFU3kawdubTBmTTql/To1pBr5h7PoiOyA='

  [mod.'github.com/aws/aws-sdk-go-v2/internal/configsources']
    version = 'v1.4.29'
    hash = 'sha256-jYjF19qwFqSLsLpFdlaOMfRmqU1vu9l07OpKoKlRzJA='

  [mod.'github.com/aws/aws-sdk-go-v2/internal/endpoints/v2']
    version = 'v2.7.29'
    hash = 'sha256-hL/HovKQp7zxU5GJPph7jFhsoB9su6AVY0lPnCYIskM='

  [mod.'github.com/aws/aws-sdk-go-v2/internal/v4a']
    version = 'v1.4.30'
    hash = 'sha256-/5GUNIcQ8AFQNuEQtkZU9TNxl6YSYMODdivW2/KDhGM='

  [mod.'github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding']
    version = 'v1.13.12'
    hash = 'sha256-YXMPMvr43AcyZw1fOeGhmNjYEfuE5xWmi/mALqjwx54='

  [mod.'github.com/aws/aws-sdk-go-v2/service/internal/checksum']
    version = 'v1.9.22'
    hash = 'sha256-WmabR8FaX2u/s3Le5oMzzOI7qAM3sa2UtmyUxui6lkA='

  [mod.'github.com/aws/aws-sdk-go-v2/service/internal/presigned-url']
    version = 'v1.13.29'
    hash = 'sha256-iITG6WwpmkK+p2ewOD3RJBX3iLPNa8vkeu7lunWUimI='

  [mod.'github.com/aws/aws-sdk-go-v2/service/internal/s3shared']
    version = 'v1.19.29'
    hash = 'sha256-D3sEAqOox+Fi/pBu//Ub9YfJZhnYhpbhj33n8QggmbI='

  [mod.'github.com/aws/aws-sdk-go-v2/service/s3']
    version = 'v1.103.3'
    hash = 'sha256-nFY8HQ454MQaN7hY7Ffv5gLMJXoNsMeaBHF/B4sRZ9Q='

  [mod.'github.com/aws/smithy-go']
    version = 'v1.27.1'
    hash = 'sha256-vhtOyv8p3w8p0gPIOOO2WiiJcSwM1KYqahPNCBuNtZY='

  [mod.'github.com/codeclysm/extract/v4']
    version = 'v4.0.0'
    hash = 'sha256-n7FeiXFznYM7OdOKqXVptCYyps04xHDQ6eAMCYCE8Ok='

  [mod.'github.com/containerd/typeurl/v2']
    version = 'v2.3.0'
    hash = 'sha256-SRFtlrQkfIrbnHFmk1nm8nw1agupjMkV56fXJGFPfHY='

  [mod.'github.com/davecgh/go-spew']
    version = 'v1.1.2-0.20180830191138-d8f796af33cc'
    hash = 'sha256-fV9oI51xjHdOmEx6+dlq7Ku2Ag+m/bmbzPo6A4Y74qc='

  [mod.'github.com/distribution/reference']
    version = 'v0.6.0'
    hash = 'sha256-gr4tL+qz4jKyAtl8LINcxMSanztdt+pybj1T+2ulQv4='

  [mod.'github.com/fsnotify/fsnotify']
    version = 'v1.10.1'
    hash = 'sha256-6LBLgsh4nKkMpgRKVsYFEaGDSU1fncBcWVSjKBdfgjU='

  [mod.'github.com/gkampitakis/ciinfo']
    version = 'v0.3.2'
    hash = 'sha256-PQNWwVCZeNEPw0kMXmV2ymf4nqZKgT5EhlIDd1J8XeI='

  [mod.'github.com/gkampitakis/go-diff']
    version = 'v1.3.2'
    hash = 'sha256-Qh2lAShlRm571xMxhAOfRoaFYzrfHmmk7RQmSiJxPbo='

  [mod.'github.com/gkampitakis/go-snaps']
    version = 'v0.5.14'
    hash = 'sha256-NYaEoENrkIW38V65zjWi6Zb0uIZysvE6oMfYt0jN2nI='

  [mod.'github.com/go-viper/mapstructure/v2']
    version = 'v2.5.0'
    hash = 'sha256-LbrCBANBprVI84M0CWrXc7rriJL5ac5VKbh58LBTw7U='

  [mod.'github.com/goccy/go-yaml']
    version = 'v1.19.2'
    hash = 'sha256-pkqkwtziwXoWlTOxJsPFdMc7Mj0mSC3Ll/xUmYAYcYE='

  [mod.'github.com/google/go-github/v63']
    version = 'v63.0.0'
    hash = 'sha256-Yl33aGOXdGthRVp8vrM3At1NqvI/J3/LE82boXJ/rQs='

  [mod.'github.com/google/go-querystring']
    version = 'v1.2.0'
    hash = 'sha256-F/Ve4oDaEqho8RryvdGSRR22/DbYHWZQa6M60n6oSYM='

  [mod.'github.com/h2non/filetype']
    version = 'v1.1.3'
    hash = 'sha256-lSX/fSbT3MVlNK7d1U6Q/lBHtGXXAQ/HY4zW6Bppqhc='

  [mod.'github.com/iancoleman/strcase']
    version = 'v0.3.0'
    hash = 'sha256-lVOk4klrikSCUviR16qcyAr6eoIbniUSfsLFOE1ZLpk='

  [mod.'github.com/inconshreveable/mousetrap']
    version = 'v1.1.0'
    hash = 'sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE='

  [mod.'github.com/juju/errors']
    version = 'v1.0.0'
    hash = 'sha256-9uZ0wNf44ilzLsvXqOsmFUpNOBFAVadj6+ZH8+QMDMk='

  [mod.'github.com/klauspost/compress']
    version = 'v1.18.6'
    hash = 'sha256-gULc+A2Clg2HnwR9UNXSIHVGdFY/aGqhf0zlvMxqaSY='

  [mod.'github.com/kr/pretty']
    version = 'v0.3.1'
    hash = 'sha256-DlER7XM+xiaLjvebcIPiB12oVNjyZHuJHoRGITzzpKU='

  [mod.'github.com/kr/text']
    version = 'v0.2.0'
    hash = 'sha256-fadcWxZOORv44oak3jTxm6YcITcFxdGt4bpn869HxUE='

  [mod.'github.com/maruel/natural']
    version = 'v1.1.1'
    hash = 'sha256-eh5sNqcnxywonQ+56UAERpugr1jNxo7qJ+y09uOMChA='

  [mod.'github.com/moby/buildkit']
    version = 'v0.30.0'
    hash = 'sha256-aOvh5SoTyxQJ0wAfkYwV2MeC35HWvrQ1+aqE53VzsjQ='

  [mod.'github.com/moznion/go-optional']
    version = 'v0.13.0'
    hash = 'sha256-dGH/c4jakHKILatmOyyl/qj4xJPSGJMqCE3UdUb5mr8='

  [mod.'github.com/opencontainers/go-digest']
    version = 'v1.0.0'
    hash = 'sha256-cfVDjHyWItmUGZ2dzQhCHgmOmou8v7N+itDkLZVkqkQ='

  [mod.'github.com/pan93412/envexpander/v3']
    version = 'v3.0.0'
    hash = 'sha256-k/ASXsh/jVp6g65TJsocIxkjb16+LbIDMpNxA3G0P88='

  [mod.'github.com/pelletier/go-toml/v2']
    version = 'v2.3.1'
    hash = 'sha256-5H8+UOtPOs+Yc+8oVT/3bugCCdbq3jFMH6eOW8dadyg='

  [mod.'github.com/pkg/errors']
    version = 'v0.9.1'
    hash = 'sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw='

  [mod.'github.com/planetscale/vtprotobuf']
    version = 'v0.6.1-0.20240319094008-0393e58bdf10'
    hash = 'sha256-L8dyNm+PCRDNADiIGKZqsPkCgB4xpLrosZjssrN+sUY='

  [mod.'github.com/pmezard/go-difflib']
    version = 'v1.0.1-0.20181226105442-5d4384ee4fb2'
    hash = 'sha256-XA4Oj1gdmdV/F/+8kMI+DBxKPthZ768hbKsO3d9Gx90='

  [mod.'github.com/rogpeppe/go-internal']
    version = 'v1.13.1'
    hash = 'sha256-fD4n3XVDNHL7hfUXK9qi31LpBVzWnRK/7LNc3BmPtnU='

  [mod.'github.com/sagikazarmark/locafero']
    version = 'v0.12.0'
    hash = 'sha256-EXk9S5Z5sYyApAzCgHIugsGMbt/pHWRfHYFZH5D+5Ws='

  [mod.'github.com/samber/lo']
    version = 'v1.53.0'
    hash = 'sha256-RCf4Buf357TTWQnMPSWKrfdJ4L/RqOHNBD0g3+VpMw8='

  [mod.'github.com/samber/mo']
    version = 'v1.17.0'
    hash = 'sha256-wEQAH1G2p7ph052KK3fZLr/RWPiLmyAh/XJi/l6YMjU='

  [mod.'github.com/spf13/afero']
    version = 'v1.15.0'
    hash = 'sha256-LhcezbOqfuBzacytbqck0hNUxi6NbWNhifUc5/9uHQ8='

  [mod.'github.com/spf13/cast']
    version = 'v1.10.0'
    hash = 'sha256-dQ6Qqf26IZsa6XsGKP7GDuCj+WmSsBmkBwGTDfue/rk='

  [mod.'github.com/spf13/cobra']
    version = 'v1.10.2'
    hash = 'sha256-nbRCTFiDCC2jKK7AHi79n7urYCMP5yDZnWtNVJrDi+k='

  [mod.'github.com/spf13/pflag']
    version = 'v1.0.10'
    hash = 'sha256-uDPnWjHpSrzXr17KEYEA1yAbizfcsfo5AyztY2tS6ZU='

  [mod.'github.com/spf13/viper']
    version = 'v1.21.0'
    hash = 'sha256-A9A8i7HH/ge4j3hw7G++HNj8BjhhpZKvxHhfY+QAxkI='

  [mod.'github.com/stretchr/testify']
    version = 'v1.11.1'
    hash = 'sha256-sWfjkuKJyDllDEtnM8sb/pdLzPQmUYWYtmeWz/5suUc='

  [mod.'github.com/subosito/gotenv']
    version = 'v1.6.0'
    hash = 'sha256-LspbjTniiq2xAICSXmgqP7carwlNaLqnCTQfw2pa80A='

  [mod.'github.com/tidwall/gjson']
    version = 'v1.18.0'
    hash = 'sha256-CO6hqDu8Y58Po6A01e5iTpwiUBQ5khUZsw7czaJHw0I='

  [mod.'github.com/tidwall/match']
    version = 'v1.1.1'
    hash = 'sha256-M2klhPId3Q3T3VGkSbOkYl/2nLHnsG+yMbXkPkyrRdg='

  [mod.'github.com/tidwall/pretty']
    version = 'v1.2.1'
    hash = 'sha256-S0uTDDGD8qr415Ut7QinyXljCp0TkL4zOIrlJ+9OMl8='

  [mod.'github.com/tidwall/sjson']
    version = 'v1.2.5'
    hash = 'sha256-OYGNolkmL7E1Qs2qrQ3IVpQp5gkcHNU/AB/z2O+Myps='

  [mod.'github.com/ulikunitz/xz']
    version = 'v0.5.15'
    hash = 'sha256-L5KYLue5U14bxUuNyhZ6lIjbda6eCQsx1V6gToqfRdk='

  [mod.'go.yaml.in/yaml/v3']
    version = 'v3.0.4'
    hash = 'sha256-NkGFiDPoCxbr3LFsI6OCygjjkY0rdmg5ggvVVwpyDQ4='

  [mod.'golang.org/x/exp']
    version = 'v0.0.0-20250911091902-df9299821621'
    hash = 'sha256-cSDirFex900mrckzB3fe18hW2Vk4/y4xKvlUWq3yoDA='

  [mod.'golang.org/x/sys']
    version = 'v0.46.0'
    hash = 'sha256-NzRXMSEk6upeudJvUEPVnw6clJ3d8UdC/vdfANWAc8g='

  [mod.'golang.org/x/text']
    version = 'v0.38.0'
    hash = 'sha256-PzREcn7yzTAJ0WBvyYL/2/r+tfoeKTY/E5HVXi/CJsU='

  [mod.'google.golang.org/protobuf']
    version = 'v1.36.11'
    hash = 'sha256-7W+6jntfI/awWL3JP6yQedxqP5S9o3XvPgJ2XxxsIeE='

  [mod.'gopkg.in/yaml.v3']
    version = 'v3.0.1'
    hash = 'sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU='
