// Code generated by listversion; DO NOT EDIT.
//go:generate go run cmd/listversion/main.go

package nodejs

import (
	"github.com/Masterminds/semver/v3"
)

// nodeVersions is a list of all the Node.js versions.
// You should never change values here.
var nodeVersions = []*semver.Version{
	semver.MustParse("20.0.0"),
	semver.MustParse("19.0.0"),
	semver.MustParse("18.0.0"),
	semver.MustParse("17.0.0"),
	semver.MustParse("16.0.0"),
	semver.MustParse("15.0.0"),
	semver.MustParse("14.0.0"),
	semver.MustParse("13.0.0"),
	semver.MustParse("12.0.0"),
	semver.MustParse("11.0.0"),
	semver.MustParse("10.0.0"),
	semver.MustParse("9.0.0"),
	semver.MustParse("8.0.0"),
	semver.MustParse("7.0.0"),
	semver.MustParse("6.0.0"),
	semver.MustParse("5.0.0"),
	semver.MustParse("4.0.0"),
}
